template: "regression/v1"
data:
  location: { { INGEST_DATA_LOCATION } }
  format: { { INGEST_DATA_FORMAT|default('parquet') } }
target_col: "T"
steps:
  split:
    split_ratios: [0.75, 0.125, 0.125]
    post_split_filter_method: steps.split.create_dataset_filter
  transform:
    transformer_method: steps.transform.transformer_fn
  train:
    using: estimator_spec
    estimator_method: steps.train.estimator_fn
  evaluate:
    validation_criteria:
      - metric: root_mean_squared_error
        threshold: 10
  register:
    model_name: "test"
    allow_non_validated_model: false
  predict:
    output_location: { { SCORED_OUTPUT_DATA_LOCATION } }
    output_format: { { SCORED_OUTPUT_DATA_FORMAT|default('parquet') } }
metrics:
  primary: "mean_absolute_error"
data_scoring:
  location: { { INGEST_SCORING_DATA_LOCATION } }
  format: { { INGEST_SCORING_DATA_FORMAT|default('parquet') } }
